# Generated by Django 4.1.2 on 2022-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_guideprofile_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='profile_picture',
            field=models.ImageField(default='images/tourist.png', upload_to='images/'),
        ),
    ]
