# Generated by Django 4.1.2 on 2022-11-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='post',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Hail', 'Hail'), ('Al Ula', 'Al Ula')], default='Riyadh', max_length=64),
        ),
    ]
