# Generated by Django 4.1.2 on 2022-11-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourApp', '0005_reservation_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tourApp.place'),
            preserve_default=False,
        ),
    ]
